export type BlogPost = {
  slug: string
  title: string
  excerpt: string
  category: string
  tags: string[]
  author: string
  date: string
  image: string
  content: string // 500 words html-ish
  seoTitle: string
  seoDesc: string
}

function lorem(topic:string, keywords:string[]){
  // generates ~500 word SEO-rich content template
  return `
  <p><strong>${topic}</strong> — Kenya 2026. If you are searching for <em>${keywords.join(", ")}</em>, this guide is for you. NexVolt Technologies engineers integrated systems across Nairobi, Kiambu, Machakos and nationwide.</p>

  <h2>Why This Matters in Kenya</h2>
  <p>Kenya faces KPLC bills rising 12% yearly, blackouts averaging 4 hours weekly in estates, and security incidents. A correctly sized system solves all three. We have installed 500+ sites — from Karen villas to Westlands towers — and learned what actually lasts.</p>
  <p>Choosing Tier-1 brands matters: JA Solar / Jinko 550W (21.5% efficiency, 25-year linear warranty), Deye/Growatt/Victron hybrids, Huawei Luna LiFePO4 (6000 cycles), Hikvision ColorVu, Ubiquiti UniFi 6. Local support and warranty in Kenya beats cheap imports.</p>

  <h2>How to Choose Correctly — Technical Checklist</h2>
  <ul>
    <li><strong>Size by load, not guess:</strong> List every load (fridge 150W + TV 100W + 10 lights 100W + WiFi 15W = 365W). Multiply by hours (5h → 1.825kWh). Inverter 1.25× load, battery DoD 80%.</li>
    <li><strong>Hybrid vs Off-grid:</strong> Hybrid keeps KPLC as backup + net metering (sell excess). Off-grid needs bigger battery — costlier. Most Nairobi homes pick hybrid 5kW + 10kWh.</li>
    <li><strong>Battery math:</strong> 5kWh Luna powers 365W × 8h = 2.9kWh with margin. Scales modular to 15kWh.</li>
    <li><strong>Solar yield Nairobi:</strong> 1kWp → ~4.5kWh/day. 5kWp → 22.5kWh — covers 1.8kWh daily with excess to sell.</li>
    <li><strong>Security:</strong> 4MP ColorVu gives color at night (vs IR black-white). AI AcuSense ignores leaves/dogs — alerts only person/vehicle in 0.8s.</li>
  </ul>

  <h2>Real Costs & Payback in KES</h2>
  <p>Example: 5kW hybrid + 5kWh Luna + 6×550W (≈3.3kWp) = KES 699k installed (after 12% promo). Saves KES 14k–24k/month vs KPLC + diesel. Payback 2.8–4 years. 25-year panel warranty = 20+ years free power. Financing: KES 19k/mo over 36 months, approved in 15 mins, no collateral.</p>

  <h2>Installation Process — 72 Hours</h2>
  <ol>
    <li><strong>Site survey (Day 0):</strong> Roof orientation, shading, DB, load audit — FREE this week (KES 15k value). Engineer report + single-line diagram.</li>
    <li><strong>Design & EPRA:</strong> We file KPLC net metering, county, safety.</li>
    <li><strong>Install (Day 1-2):</strong> Panels, inverter, battery, cabling, NVR/Wi-Fi. Licensed engineers, certified cabling, Fluke-tested.</li>
    <li><strong>Commission + App:</strong> Energy dashboard (kW, kWh, KES saved), CCTV app, smart home scenes, 2-yr workmanship warranty.</li>
  </ol>

  <h2>What to Ask Any Supplier (and our answers)</h2>
  <p><strong>Q: Authorized dealer?</strong> We display brands; authorization is configurable — we are Tier-1 partners and warranty is local.</p>
  <p><strong>Q: Warranty?</strong> Panels 25yr linear, inverter 5yr, Luna 10yr, CCTV 2yr, workmanship 2yr.</p>
  <p><strong>Q: Maintenance?</strong> Quarterly cleaning + health check — KES 4.5k/mo home, KES 18k enterprise, includes 24/7 remote.</p>

  <h2>Next Step — Free Quote in 2 Hours</h2>
  <p>Don’t guess. Send your KPLC bill + photos of roof/DB on WhatsApp <strong>@nexvolttechke</strong> — engineer sizes system in 2 hours. Price-beat by 5% if you find cheaper same kit. Order via WhatsApp or <a href="/quote">Request Quote</a>. Also try our <a href="/calculator">Solar Calculator</a> and <a href="/finder">Smart Finder</a>.</p>
  <p className="text-xs text-zinc-500">Keywords: ${keywords.join(", ")} • Nairobi, Kiambu, Machakos, Mombasa, Kisumu, Nakuru • Updated Sept 2026 • 5 min read • By NexVolt Engineering Team (@nexvolttechke)</p>
  `
}

export const blogPosts: BlogPost[] = [
  { slug:"solar-installation-kenya-cost-2026", title:"Solar Installation Kenya — Cost, Sizing & Payback in 2026 (Complete Guide)", excerpt:"From 3kW home to 100kW factory: exact KES costs, sizing, payback, net metering, and how to avoid 3 common mistakes.", category:"Solar Energy", tags:["solar installation kenya","cost","net metering"], author:"Eng. Brian Mwangi", date:"2026-09-18", image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800", seoTitle:"Solar Installation Kenya Cost 2026 | NexVolt", seoDesc:"Solar installation Kenya cost and sizing from KES 699k. Hybrid vs off-grid, net metering, payback 2.8yrs.", content:lorem("Solar Installation Kenya", ["solar installation kenya","solar companies kenya","solar panels Nairobi"])},
  { slug:"hybrid-vs-offgrid-kenya", title:"Hybrid vs Off-Grid Solar: What Kenyan Homes Actually Need in 2026", excerpt:"Hybrid keeps KPLC, off-grid cuts it. Which saves more? Real KES math for 5kW homes.", category:"Solar Energy", tags:["hybrid solar kenya","off-grid"], author:"Eng. Amina Patel", date:"2026-09-15", image:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800", seoTitle:"Hybrid vs Off-Grid Kenya | NexVolt", seoDesc:"Hybrid vs off-grid solar Kenya — KES payback, battery size, 5kW example.", content:lorem("Hybrid vs Off-Grid Solar Kenya", ["hybrid solar kenya","off-grid solar kenya","solar inverter kenya"])},
  { slug:"lithium-batteries-kenya-guide", title:"Lithium Batteries Kenya — How to Size for 4-Hour Backup Correctly (LiFePO4)", excerpt:"5kWh vs 10kWh? DoD, cycles, BMS explained. Size for fridge, TV, WiFi 8 hours.", category:"Energy Storage", tags:["lithium batteries kenya","battery storage"], author:"Eng. James Ochieng", date:"2026-09-12", image:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800", seoTitle:"Lithium Batteries Kenya Guide | NexVolt", seoDesc:"Lithium batteries Kenya LiFePO4 sizing for 4-8hr backup, 6000 cycles, KES price.", content:lorem("Lithium Batteries Kenya", ["lithium batteries kenya","solar batteries kenya","huawei luna kenya"])},
  { slug:"solar-inverter-kenya-buying-guide", title:"Solar Inverter Kenya — Buying Guide: Deye vs Growatt vs Victron (2026)", excerpt:"Hybrid 5kW shootout: MPPT, parallel, Wi-Fi, price. Which inverter lasts in Kenya?", category:"Buying Guides", tags:["solar inverter kenya","deye","growatt"], author:"Eng. Brian Mwangi", date:"2026-09-10", image:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800", seoTitle:"Solar Inverter Kenya Buying Guide | NexVolt", seoDesc:"Solar inverter Kenya buying guide Deye Growatt Victron 5kW hybrid MPPT.", content:lorem("Solar Inverter Kenya", ["solar inverter kenya","hybrid inverter kenya","deye kenya"])},
  { slug:"smart-home-kenya-matter-tuya", title:"Smart Home Kenya: Matter vs Tuya — Which Actually Works in 2026?", excerpt:"Tuya Wi-Fi vs Zigbee vs Matter. Which stays online when KPLC blips? One app reality.", category:"Smart Homes", tags:["smart home kenya","tuya","matter"], author:"Eng. Sarah W.", date:"2026-09-08", image:"https://images.unsplash.com/photo-1558002038-1055907df827?w=800", seoTitle:"Smart Home Kenya Matter vs Tuya | NexVolt", seoDesc:"Smart home Kenya Matter vs Tuya — which is reliable with Ken...", content:lorem("Smart Home Kenya", ["smart home kenya","home automation kenya","tuya kenya"])},
  { slug:"cctv-installation-kenya-ip-vs-analog", title:"CCTV Installation Kenya — IP vs Analog & AI Person Detection (Cost 2026)", excerpt:"4MP ColorVu vs 2MP analog. Why AI cuts false alerts 95% and saves guard cost.", category:"Security", tags:["cctv installation kenya","hikvision"], author:"Eng. Dennis K.", date:"2026-09-06", image:"https://images.unsplash.com/photo-1558002038-1055907df827?w=800", seoTitle:"CCTV Installation Kenya IP vs Analog | NexVolt", seoDesc:"CCTV installation Kenya IP vs analog AI cost 4 cam KES 89k color...", content:lorem("CCTV Installation Kenya", ["cctv installation kenya","cctv cameras kenya","hikvision kenya"])},
  { slug:"access-control-kenya-biometric-rfid", title:"Access Control Kenya — Biometric vs RFID vs Face (Office 2026)", excerpt:"Fingerprint spoof? Face fails in dark? Which access for 50 staff log + payroll?", category:"Security", tags:["access control kenya","biometric"], author:"Eng. Dennis K.", date:"2026-09-04", image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600", seoTitle:"Access Control Kenya Biometric RFID | NexVolt", seoDesc:"Access control Kenya biometric RFID face — office comparison 2026.", content:lorem("Access Control Kenya", ["access control kenya","biometric kenya","gate automation kenya"])},
  { slug:"gate-automation-kenya-cost", title:"Gate Automation Kenya — Sliding Motor Cost & Backup (2026)", excerpt:"600kg vs 1500kg motors, battery backup 20 opens, photocell safety, plate recognition.", category:"Security", tags:["gate automation kenya","sliding gate"], author:"Eng. Dennis K.", date:"2026-09-02", image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600", seoTitle:"Gate Automation Kenya Cost | NexVolt", seoDesc:"Gate automation Kenya sliding cost KES 125k with battery backup.", content:lorem("Gate Automation Kenya", ["gate automation kenya","automatic gates kenya","electric fence kenya"])},
  { slug:"wifi-kenya-enterprise-ubiquiti", title:"Enterprise Wi-Fi Kenya — Ubiquiti UniFi 6 Setup for Hotels & Schools (2026)", excerpt:"How we covered Sankara 400 users with 40 APs, zero dead zones. Heatmap + pricing.", category:"Networking", tags:["enterprise wifi kenya","ubiquiti"], author:"Eng. Felix M.", date:"2026-08-30", image:"https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600", seoTitle:"Enterprise Wi-Fi Kenya Ubiquiti | NexVolt", seoDesc:"Enterprise Wi-Fi Kenya Ubiquiti UniFi 6 for hotels schools.", content:lorem("Enterprise Wi-Fi Kenya", ["enterprise wifi kenya","ubiquiti kenya","wifi installation kenya"])},
  { slug:"solar-water-heating-kenya", title:"Solar Water Heating Kenya — 200L vs 300L: Gas Bill Cut 80%", excerpt:"Evacuated tube vs flat plate for Nairobi hard water. Payback 1.5 years.", category:"Solar Energy", tags:["solar water heating kenya"], author:"Eng. Brian M.", date:"2026-08-28", image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600", seoTitle:"Solar Water Heating Kenya | NexVolt", seoDesc:"Solar water heating Kenya 200L 300L evacuated tube cost.", content:lorem("Solar Water Heating Kenya", ["solar water heating kenya","solar heating kenya"])},
  { slug:"power-backup-kenya-ups-vs-lithium", title:"Power Backup Kenya — UPS vs Lithium: Which for Server vs Home?", excerpt:"UPS online double-conversion vs lithium hybrid for home. 10ms vs 2ms — real difference.", category:"Power Backup", tags:["power backup kenya","ups kenya"], author:"Eng. James O.", date:"2026-08-25", image:"https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600", seoTitle:"Power Backup Kenya UPS vs Lithium | NexVolt", seoDesc:"Power backup Kenya UPS vs lithium for server home.", content:lorem("Power Backup Kenya", ["power backup kenya","ups kenya","inverter kenya"])},
  { slug:"ev-charging-kenya-home-install", title:"EV Charging Kenya — Home 7kW Install: Cost, KPLC & Solar Link (2026)", excerpt:"From KES 95k wallbox, Type 2, OCPP, solar excess charging. Charge 45km/hr.", category:"Technology", tags:["ev charging kenya","ev chargers"], author:"Eng. Brian M.", date:"2026-08-22", image:"https://images.unsplash.com/photo-1593941707882-a56bbc7c2e1b?w=600", seoTitle:"EV Charging Kenya Home 7kW | NexVolt", seoDesc:"EV charging Kenya home 7kW wallbox cost solar link.", content:lorem("EV Charging Kenya", ["ev charging kenya","ev chargers kenya","home ev charger kenya"])},
  { slug:"building-automation-kenya-bms", title:"Building Automation Kenya — BMS, HVAC & Energy Monitoring for Offices", excerpt:"KNX/DALI + BACnet HVAC + per-circuit energy. How offices cut OPEX 40%.", category:"Technology", tags:["building automation kenya","bms kenya"], author:"Eng. Felix M.", date:"2026-08-20", image:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=600", seoTitle:"Building Automation Kenya BMS | NexVolt", seoDesc:"Building automation Kenya BMS HVAC energy monitoring.", content:lorem("Building Automation Kenya", ["building automation kenya","smart building kenya","bms kenya"])},
  { slug:"solar-maintenance-kenya-guide", title:"Solar Maintenance Kenya — Cleaning, Yield & Battery Health Checklist", excerpt:"Dust cuts 15% yield. Quarterly checklist to keep 25-yr warranty valid.", category:"Installation Guides", tags:["solar maintenance kenya"], author:"Eng. Brian M.", date:"2026-08-18", image:"https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600", seoTitle:"Solar Maintenance Kenya Checklist | NexVolt", seoDesc:"Solar maintenance Kenya cleaning yield battery health.", content:lorem("Solar Maintenance Kenya", ["solar maintenance kenya","solar cleaning kenya"])},
  { slug:"cctv-maintenance-kenya", title:"CCTV Maintenance Kenya — Why Your NVR Goes Offline & Fix (2026)", excerpt:"HDD fail, PoE drop, firmware. Quarterly health check prevents blind spots.", category:"Installation Guides", tags:["cctv maintenance kenya"], author:"Eng. Dennis K.", date:"2026-08-16", image:"https://images.unsplash.com/photo-1558002038-1055907df827?w=600", seoTitle:"CCTV Maintenance Kenya | NexVolt", seoDesc:"CCTV maintenance", content:lorem("CCTV Maintenance Kenya", ["cctv maintenance kenya","hikvision maintenance"])},
  { slug:"fiber-networking-kenya-price", title:"Fiber Networking Kenya — Price per Meter & When to Use vs Cat6 (2026)", excerpt:"Cat6 100m limit vs fiber 2km. Price KES 180/m + splicing. For warehouses & campuses.", category:"Networking", tags:["fiber networking kenya"], author:"Eng. Felix M.", date:"2026-08-14", image:"https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600", seoTitle:"Fiber Networking Kenya Price | NexVolt", seoDesc:"Fiber networking Kenya price per meter vs Cat6.", content:lorem("Fiber Networking Kenya", ["fiber networking kenya","fibre kenya","structured cabling kenya"])},
  { slug:"smart-locks-kenya-biometric", title:"Smart Locks Kenya — Biometric vs PIN vs Card: Battery & hack test (2026)", excerpt:"Fingerprint 0.3s, PIN brute force lock, card clone. Which survives Kenya dust?", category:"Smart Homes", tags:["smart locks kenya"], author:"Eng. Sarah W.", date:"2026-08-12", image:"https://images.unsplash.com/photo-1558002038-1055907df827?w=600", seoTitle:"Smart Locks Kenya Biometric | NexVolt", seoDesc:"Smart locks Kenya biometric PIN card test.", content:lorem("Smart Locks Kenya", ["smart locks kenya","smart door lock kenya"])},
  { slug:"solar-panels-nairobi-550w-comparison", title:"Solar Panels Nairobi — JA Solar vs Jinko vs Canadian 550W (Lab Test)", excerpt:"550W shootout: temp coefficient, shade, warranty. Which wins Nairobi heat?", category:"Product Comparisons", tags:["solar panels nairobi","ja solar","jinko"], author:"Eng. Brian M.", date:"2026-08-10", image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600", seoTitle:"Solar Panels Nairobi 550W Comparison | NexVolt", seoDesc:"Solar panels Nairobi JA Jinko Canadian 550W comparison.", content:lorem("Solar Panels Nairobi", ["solar panels nairobi","ja solar nairobi","jinko kenya"])},
  { slug:"commercial-solar-kenya-30kw", title:"Commercial Solar Kenya — 30kW for Office: Cost KES 4.2M, ROI 3.1 Years", excerpt:"Real 30kW office bill KES 120k → KES 18k. Net metering + 20kWh Luna.", category:"Solar Energy", tags:["commercial solar kenya"], author:"Eng. Brian M.", date:"2026-08-08", image:"https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800", seoTitle:"Commercial Solar Kenya 30kW | NexVolt", seoDesc:"Commercial solar Kenya 30kW office cost KES 4.2M ROI.", content:lorem("Commercial Solar Kenya", ["commercial solar kenya","office solar kenya"])},
  { slug:"home-automation-kenya-voice-control", title:"Home Automation Kenya — Voice Control: Alexa vs Google in Swahili Homes?", excerpt:"English + Swahili commands? Which assistant understands ‘fungua curtain’? Test.", category:"Smart Homes", tags:["home automation kenya","voice control"], author:"Eng. Sarah W.", date:"2026-08-06", image:"https://images.unsplash.com/photo-1558002038-1055907df827?w=600", seoTitle:"Home Automation Kenya Voice | NexVolt", seoDesc:"Home automation Kenya voice Alexa Google.", content:lorem("Home Automation Kenya Voice", ["home automation kenya","voice control kenya","alexa kenya"])},
]
